=== Compatibility

==== *MUST* Don’t Break Backward Compatibility

Change APIs, but keep all consumers running. Consumers usually have independent release lifecycles, focus on stability, and avoid changes that do not provide additional value. APIs are service contracts that cannot be broken via unilateral decisions.

There are two techniques to change APIs without breaking them:

- follow rules for compatible extensions
- introduce new API versions and still support older versions

We strongly encourage using compatible API extensions and discourage versioning.
With Postel’s Law in mind, here are some rules for providers and consumers that allow us to make compatible changes without versioning:

==== *MUST* Prepare Clients for Compatible API Extensions (the Robustness Principle)

How to do this:

* Ignore new and unknown fields in the payload (see also  http://martinfowler.com/bliki/TolerantReader.html[Fowler’s TolerantReader] post)
* Be prepared for new enum values declared with [`x-extensible-enum`]
* Provide default behavior for unknown values, if applicable
* Follow the redirect when the server returns an “HTTP 301 Moved Permanently” response code
* Be prepared to handle HTTP status codes not explicitly specified in endpoint definitions! Note also, that status codes are extensible -- default handling is how you would treat the corresponding x00 code (see https://tools.ietf.org/html/rfc7231#section-6[RFC7231  Section 6])

==== *MUST* Always Return JSON Objects As Top-Level Data Structures To Support Extensibility

In a response body, you must always return a JSON objects (and not e.g. an array) as a top level data structure to support future extensibility. JSON objects support compatible extension by additional attributes. This allows you to easily extend your response and e.g. add pagination later, without breaking backwards compatibility.

==== *MUST* Do Not Use URI Versioning

With URI versioning a (major) version number is included in the path, e.g.
/v1/customers. The consumer has to wait until the provider has been released
and deployed. If the consumer also supports hypermedia links — even in their
APIs — to drive workflows (HATEOAS), this quickly becomes complex. So does
coordinating version upgrades — especially with hyperlinked service
dependencies — when using URL versioning. To avoid this tighter coupling and
complexer release management we do not use URI versioning, and go instead with
media type versioning and content negotiation (see above).