=== Pagination

==== *MUST* Support Pagination

Access to lists of data items must support pagination for best client side batch processing and iteration experience. This holds true for all lists that are (potentially) larger than just a few hundred entries.

There are two page iteration techniques:

* http://developer.infoconnect.com/paging-results-limit-and-offset[Offset/Limit-based pagination]: numeric offset identifies the first page entry (using `page` and `per-page` query parameters for exemple)
* https://dev.twitter.com/overview/api/cursoring[Cursor-based] — aka key-based — pagination: a unique key element identifies the first page entry (see also  https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging[Facebook’s guide])

The technical conception of pagination should also consider user experience related issues. As mentioned in this https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/[article], jumping to a specific page is far less used than navigation via next/previous page links. This favours cursor-based over offset-based pagination.